# docker-compose.yml

# jenkins instance
version: '3.3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: palisades-jenkins
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  # nginx for reverse proxy and other hosting if needed
  nginx:
    image: nginx:latest
    build: ./nginx/
    container_name: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      - deploy-network

# adding a network to keep everything encapsulated
networks: 
  deploy-network:
    driver: bridge
